### ISSUE TITLE
Write Fence support

### ISSUE THREAD

**Issue by Slava** [Slava/meteor-rethinkdb#1]
Implement the write fence support. This way, we can write better tests and preserve the properties guaranteed by DDP for method invocations.

"The write fence returns when all db updates produced by the RPC hit the observers"

**Comment by Slava** [comment]
Here is what I asked from the RethinkDB team, roughly describes the problem:

> One of the properties of DDP: every RPC has 2 response messages in case of a success. The first message, "result", contains a return value of the call. The second message, "updated", confirms that all db changes made by the call visible to the client has been propagted to the clients in a form of DDP's "added/changed/removed" messages.
> 
> We have an implementation of this in Meteor for MongoDB. Roughly, the way it works, when a write to Mongo occurs, we want to know when we will process it in our stream of updates from oplog. Since all oplog records have an id (timestamp + a number), we can look at the latest timestamp and then declare that we "processed" all the updates for the RPC, when we reach that timestamp.
> 
> In Rethink, changefeeds don't have any revision number. Neither you can get the latest revision number in the database.
> 
> This becomes an obstacle in my implementation of DDP. Are there any other features of RethinkDB I can use to achieve this effect?
> 
> Shortly: how do I know that my write was propagated to change-feeds?

**Comment by Slava** [comment]
So after talking in RethinkDB channel. Here are the possible solutions:
- use change feeds w/o squashed updates. remember the type of updates and try to catch them out in the wild (possibly incorrect for various conditions of multiple queries writing concurrently)
- wait for Rethink 2.2, hoping that the writes will return internal revision numbers and changefeeds will have a special flag to return revision numbers
- simulate revisions in the application layer, by keeping a special "_timestamp" field on every document

**Comment by Slava** [comment]
My new plan is to have synthetic events (one extra document per table) and use the `r.now()` function to rely on the server time. Hopefully they have their distributed time figured out.

**Comment by just-be-dev** [comment]
Testing that will be tricky. Did they seem open to adding the internal revision number?

**Comment by Slava** [comment]
Yay, this is fixed in aeabafb1404ac284a34e3a7b08e0114fedfe87a0. Would love to have more tests on reactivity but so far this seems to be working.
