### ISSUE TITLE
Implications of joins for reactive performance 

### ISSUE THREAD

**Issue by rclai** [Slava/meteor-rethinkdb#16]
I was thinking about how nice it would be to have joins but then realized is this going to have a negative effect on reactivity performance-wise? 

For example, if I joined on three tables on the client, and just one of the documents in any of those tables changes, is that going to cause the entire join query to re-run? And if I was rendering that data in Blaze, would it all need to re-render? 

How will fine grained reactivity work in the context of joins?

**Comment by Slava** [comment]
I have no idea what this issue has to do with this repo.

The answer is - incrementally recompute queries. There is no magic in the world.
