### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by puruzio** [Slava/meteor-rethinkdb#25]
I cloned the meteor-webpack-react-kickstart package and added the simple:rethink Meteor package to it in order to try RethinkDB.

(The link is listed below for each of this sample projects. I was able to successfully run them individually.
https://www.npmjs.com/package/meteor-webpack-react-kickstart 
https://github.com/Slava/meteor-rethinkdb/)

When I run Meteor in the Terminal, the list of Cities are properly retrieved from the RethinkDB table and displayed in the browser as intended, but a few seconds later, without me doing anything, the error message appears in the Terminal, and any new data (city) that I add using data_add_button() doesn't get persisted to the local RethinkDB instance.

Please refer to the stack trace below.

I did a search for "for (_i = 0, _len = _ref.length; _i < _len; _i++) " in Webstorm in all project files, but no match was found.

[Stack Trace]
<Stack
    W20151015-21:28:53.274(-7)? (STDERR)       
        /Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/errors.js:97
 W20151015-21:28:53.274(-7)? (STDERR)       **for (_i = 0, _len = _ref.length; _i < _len; _i++) {
 W20151015-21:28:53.275(-7)? (STDERR)                               ^
 W20151015-21:28:53.279(-7)? (STDERR) TypeError: Cannot read property 'length' of undefined**
W20151015-21:28:53.280(-7)? (STDERR)     at /Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/errors.js:97:31
W20151015-21:28:53.280(-7)? (STDERR)     at composeTerm (/Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/errors.js:102:7)
W20151015-21:28:53.280(-7)? (STDERR)     at RqlQueryPrinter.printQuery (/Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/errors.js:87:12)
W20151015-21:28:53.281(-7)? (STDERR)     at RqlCompileError.RqlServerError (/Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/errors.js:31:100)
W20151015-21:28:53.281(-7)? (STDERR)     at new RqlCompileError (/Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/errors.js:62:50)
W20151015-21:28:53.281(-7)? (STDERR)     at mkErr (/Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/util.js:173:10)
W20151015-21:28:53.281(-7)? (STDERR)     at TcpConnection.Connection._processResponse (/Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/net.js:128:16)
W20151015-21:28:53.281(-7)? (STDERR)     at TcpConnection.Connection._data (/Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/net.js:105:12)
W20151015-21:28:53.282(-7)? (STDERR)     at Socket.<anonymous> (/Users/user/.meteor/packages/simple_rethink/.0.0.2.1hw50se++os+web.browser+web.cordova/npm/node_modules/rethinkdb/net.js:505:32)
W20151015-21:28:53.283(-7)? (STDERR)     at Socket.emit (events.js:95:17)
W20151015-21:28:53.283(-7)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20151015-21:28:53.283(-7)? (STDERR)     at Socket.emit (events.js:92:17)
W20151015-21:28:53.283(-7)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20151015-21:28:53.283(-7)? (STDERR)     at emitReadable (_stream_readable.js:423:5)
W20151015-21:28:53.283(-7)? (STDERR)     at readableAddChunk (_stream_readable.js:166:9)
W20151015-21:28:53.283(-7)? (STDERR)     at Socket.Readable.push (_stream_readable.js:128:10)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

My codes relevant to this issue can be found here.

http://stackoverflow.com/questions/33163033/meteor-rethinkdb-project-cannot-read-property-length-of-undefined

**Comment by Slava** [comment]
I don't think I can help you with a webpack starter kit, I have no idea what it is and don't have time to look at it.

If you can narrow down the bug to a simple reproduction app that only uses stock Meteor with this package, then we can look at it.
