### ISSUE TITLE
Command line tool integration

### ISSUE THREAD

**Issue by ccorcos** [Slava/meteor-rethinkdb#6]
I think this project is a good motivation to build an API so packages can define commands that hook into the commandline tool. This way, we dont have to manually start, stop, reset, and configure the database for each project.

**Comment by Slava** [comment]
I think the general direction is correct, but the proposal would need actual technical details. Closing this.

**Comment by ccorcos** [comment]
Yeah. Sadly, I don't know those technical details... I'm just trying to get the conversation started somewhere. 

Right now, I'm playing around with Neo4j. I'm not trying to do much on the client, but I'm using it on the server. It would be nice if I could integrate starting and stopping the database into the meteor CLI...

Also, when building separate microservices, its a little awkward to have to run each of them individually... Just some thoughts...

**Comment by Slava** [comment]
This is a separate project of a bigger scale and I have no desire to track it here. You are welcome to do it on meteor/meteor repository.

**Comment by ccorcos** [comment]
Ok. Sounds like a plan.

**Comment by ccorcos** [comment]
https://github.com/meteor/meteor/issues/4324
