### ISSUE TITLE
meteor add no such package

### ISSUE THREAD

**Issue by funston** [Slava/meteor-rethinkdb#7]
%  meteor add simple:rethink
 => Errors while parsing arguments:           

While adding package simple:rethink:
error: no such package

**Comment by Slava** [comment]
It is not published yet. I am still working on the package to reach a state when it is not too flaky. I am still aiming to get a better latency compensation support.

**Comment by Slava** [comment]
I published the first version. https://atmospherejs.com/simple/rethink
